WITH S AS
(SELECT A.CAR_ID, A.CAR_TYPE, ROUND(DAILY_FEE*30 / 100 * (100 - DISCOUNT_RATE)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV') AND B.CAR_ID NOT IN(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') AND DURATION_TYPE LIKE "30%" 

)
SELECT DISTINCT CAR_ID, CAR_TYPE, FEE
FROM S
WHERE FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

/*
     자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 
     2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 
     30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
*/