-- 코드를 입력하세요
SELECT 
    DATE_FORMAT(B.SALES_DATE, '%Y') AS YEAR,
    DATE_FORMAT(B.SALES_DATE, '%m') AS MONTH,
    COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT A.USER_ID) / 
          (SELECT COUNT (*) 
           FROM USER_INFO AS C WHERE JOINED LIKE "2021%"), 1) AS PURCHASED_RATIO
FROM USER_INFO AS A JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
WHERE YEAR(A.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

# SELECT DATE_FORMAT(O.SALES_DATE, '%Y') AS YEAR,
#         DATE_FORMAT(O.SALES_DATE, '%m') AS MONTH,
#         COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
#         ROUND(COUNT(DISTINCT U.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE joined LIKE '2021%'), 1) AS PUCHASED_RATIO
# FROM USER_INFO U
# JOIN ONLINE_SALE O
# ON U.USER_ID = O.USER_ID
# WHERE U.JOINED LIKE '2021%'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH
# ;
 



/*
    요구사항 
    2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수 년, 월 별로 출력
    회원의 비율은 소수점 두번째자리에서 반올림하고, 전체 결과는 년을 기준으로 오름차순 정렬해주시고 년이 같다면 월을 기준으로 오름차순 정렬
    USER_INFO 
    USER_ID	GENDER	AGE	JOINED
    
    ONLINE_SALE 
    ONLINE_SALE_ID	USER_ID	PRODUCT_ID	SALES_AMOUNT	SALES_DATE
*/