# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(USER_ID) AS PURCHASED_USERS, COUNT(USER_ID)/

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT A.USER_ID)/(SELECT COUNT(C.USER_ID) FROM USER_INFO AS C WHERE C.JOINED LIKE "2021%"),1) AS PURCHASED_RATIO
FROM USER_INFO AS A JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID
WHERE A.JOINED LIKE "2021%"
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH