-- 코드를 입력하세요
SELECT 
    DISTINCT CAR_ID, 
    IF(CAR_ID NOT IN 
       (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE "2022-10-16">= START_DATE AND "2022-10-16"<= END_DATE
        GROUP BY CAR_ID), "대여 가능", "대여중") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC
