WITH A AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
),
B AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS FIRST_HALF_TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
)
SELECT A.FLAVOR
FROM A
JOIN B ON A.FLAVOR = B.FLAVOR
ORDER BY JULY_TOTAL + FIRST_HALF_TOTAL DESC
LIMIT 3
