-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D, SKILLCODES S
WHERE (SKILL_CODE & CODE) > 0 AND CATEGORY = "Front End"
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY id

# SELECT  ID
#         ,EMAIL
#         ,FIRST_NAME
#         ,LAST_NAME
# FROM DEVELOPERS D, SKILLCODES S
# WHERE 1 = 1
#     AND (SKILL_CODE & S.CODE) > 0