select year(a.DIFFERENTIATION_DATE) as YEAR, abs(b.MAX_SIZE - a.SIZE_OF_COLONY) as YEAR_DEV, a.ID
from ECOLI_DATA as a left join 
(select year(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) AS MAX_SIZE
 FROM ECOLI_DATA 
 GROUP BY year(DIFFERENTIATION_DATE)) as b
on year(a.DIFFERENTIATION_DATE)=b.YEAR
ORDER BY YEAR, YEAR_DEV